import userRoutes from './routes/userRoutes.js';
import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import dns from 'node:dns';
import { errors } from 'celebrate';
import { connectMongoDB } from './db/connectMongoDB.js';
import notesRoutes from './routes/notesRoutes.js';
import { notFoundHandler } from './middleware/notFoundHandler.js';
import { errorHandler } from './middleware/errorHandler.js';
import authRoutes from './routes/authRoutes.js';
import cookieParser from 'cookie-parser';
import { logger } from './middleware/logger.js';
const app = express();
const PORT = process.env.PORT || 3000;

app.use(logger);
app.use(express.json());
app.use(cors());
app.use(cookieParser());
app.use(notesRoutes);
app.use(authRoutes);
app.use(userRoutes);
app.use(notFoundHandler);
app.use(errors());
app.use(errorHandler);
dns.setServers(['8.8.8.8', '8.8.4.4']);
await connectMongoDB();
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
